---
sources:
  - name: postfix # Just a name to identify the source
    stats_interval: 8h # Minimum interval between stats logging. Omit to skip.
    syslog: &syslog # Syslog configuration
      tag: dgblist # syslog tag
      facility: local0 # Facility local0, local1... mail... Not all allowed.
      level: debug # minimum level. Be careful if you are logging to the same facility your logs are from
                   # as there are Debugs messages reporting the text matching a regexp.
    nftables_set: &blackhole
      table: filter # nftables table
      name: blackhole # name of the set
      type: ipv4 # Or ipv6
    logfile: /var/log/mail.log # Log file to watch
    patterns: # Regexp patterns. Golang syntax https://github.com/google/re2/wiki/Syntax
      - 'lost connection after (?:CONNECT|HELO|STARTTLS|EHLO|DATA|UNKNOWN) from [^[:space:]]+\[([0-9\.:a-f]+)\]'
      - 'timeout after CONNECT from [^[:space:]]+\[(0-9\.:a-f]+)\]'
      - 'NOQUEUE: reject: .* from [^[:space:]]+\[([0-9\.:a-f]+)\]'
      - 'warning: non-SMTP command from [^[:space:]]+\[([0-9\.:a-f]+)\]'
    whitelist: &whitelist # These IPs will not be added even if matched.
      - 127.0.0.1
  - name: blacklist # Another source
    debug: false
    syslog: *syslog
    nftables_set: *blackhole
    logfile: /var/log/messages
    patterns:
      - 'kernel: Blacklist: .*SRC=([0-9\.:a-f]+)'
    addresses_whitelist: *whitelist
  - name: auth
    debug: true
    syslog: *syslog
    nftables_set: *blackhole
    logfile: /var/log/auth.log
    patterns:
      - 'pam_unix\(sshd:auth\): authentication failure; .*rhost=([0-9\.:a-f]+)'
    whitelist: *whitelist
